# Análisis exploratorio del rendimiento de jugadores - FIFA World Cup 2026

## 1. Importación de librerías

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## 2. Carga y selección de columnas

In [2]:
columnas_seleccionadas = [
    'player_id',
    'match_id',
    'match_date',
    'team',
    'opponent_team',
    'position',
    'preferred_foot',
    'tournament_stage',
    'match_result',
    'age',
    'market_value_eur',
    'minutes_played',
    'goals',
    'assists',
    'expected_goals_xg',
    'pass_accuracy',
    'distance_covered_km',
    'player_rating'
]

In [3]:
data = pd.read_csv(
    'fifa_world_cup_2026_player_performance.csv',
    usecols=columnas_seleccionadas
)
data.head()

,player_id,age,team,position,preferred_foot,market_value_eur,match_id,match_date,opponent_team,tournament_stage,match_result,minutes_played,goals,assists,expected_goals_xg,pass_accuracy,distance_covered_km,player_rating
0,P00055,26,Spain,Goalkeeper,Left,4384884,M00001,2026-07-10,South Africa,Group Stage,W,72,0,0,0.00,0.59,7.8,5.6
1,P00070,19,Spain,Midfielder,Right,4918927,M00001,2026-07-10,South Africa,Group Stage,W,90,0,0,0.01,0.89,10.4,5.7
2,P00066,18,Spain,Midfielder,Left,125015698,M00001,2026-07-10,South Africa,Group Stage,W,73,1,0,0.08,0.85,8.8,8.3
3,P00073,20,Spain,Forward,Right,11805512,M00001,2026-07-10,South Africa,Group Stage,W,80,1,1,0.00,0.67,9.6,6.9
4,P00059,23,Spain,Defender,Left,13325174,M00001,2026-07-10,South Africa,Group Stage,W,79,0,0,0.00,0.76,7.5,5.7

# Descripción del Dataset

El dataset contiene información inventada sobre el desempeño individual de los jugadores durante los partidos de la Copa Mundial de la FIFA 2026. Las columnas seleccionadas describen el contexto del partido, las características del jugador y diferentes indicadores de rendimiento.

In [4]:
data.shape # Información sobre la cantidad de filas y columnas del dataset.

(54600, 18)

In [5]:
data.info() # Muestra el tipo de dato de cada columna y la cantidad de valores no nulos.

<class 'pandas.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            54600 non-null  str
 1   age                  54600 non-null  int64
 2   team                 54600 non-null  str
 3   position             54600 non-null  str
 4   preferred_foot       54600 non-null  str
 5   market_value_eur     54600 non-null  int64
 6   match_id             54600 non-null  str
 7   match_date           54600 non-null  str
 8   opponent_team        54600 non-null  str
 9   tournament_stage     54600 non-null  str
 10  match_result         54600 non-null  str
 11  minutes_played       54600 non-null  int64
 12  goals                54600 non-null  int64
 13  assists              54600 non-null  int64
 14  expected_goals_xg    54600 non-null  float64
 15  pass_accuracy        54600 non-null  float64
 16  distance_covered_km  54600 non-null  float64
 17  player_rating        54600 non-null  float64
dtypes: float64(4), int64(5), str(9)
memory usage: 7.5 MB

In [6]:
data.sample(10) # Trae 10 filas aleatorias del dataset.

,player_id,age,team,position,preferred_foot,market_value_eur,match_id,match_date,opponent_team,tournament_stage,match_result,minutes_played,goals,assists,expected_goals_xg,pass_accuracy,distance_covered_km,player_rating
44005,P00540,23,Colombia,Midfielder,Right,25861649,M00847,2026-07-02,Brazil,Round of 16,W,18,0,0,0.0,0.90,3.0,7.2
27724,P00281,30,Denmark,Forward,Right,25131000,M00534,2026-07-20,Cameroon,Group Stage,L,80,0,0,0.0,0.82,7.7,5.8
41551,P00190,23,Portugal,Defender,Right,2064213,M00800,2026-07-23,Scotland,Round of 16,W,61,0,0,0.0,0.75,6.1,6.4
23004,P00753,25,Costa Rica,Forward,Right,15706272,M00443,2026-06-29,Morocco,Group Stage,L,0,0,0,0.0,0.82,0.0,0.0
31414,P00023,24,France,Forward,Right,23420128,M00605,2026-06-21,Qatar,Round of 32,D,77,0,0,0.0,0.75,8.8,6.7
54080,P00443,23,Scotland,Goalkeeper,Right,13160802,M01041,2026-07-10,Saudi Arabia,Final,W,90,0,0,0.0,0.63,8.9,6.6
22015,P01058,21,Morocco,Midfielder,Left,16376317,M00424,2026-07-02,Ghana,Group Stage,L,0,0,0,0.0,0.79,0.0,0.0
16627,P00795,28,Panama,Midfielder,Right,21025701,M00320,2026-07-04,Peru,Group Stage,L,18,0,0,0.0,0.80,3.0,6.1
51827,P00610,27,Ecuador,Defender,Right,11867067,M00997,2026-07-01,Turkey,Semi Finals,W,45,0,0,0.0,0.82,4.5,6.7
14065,P01068,28,Nigeria,Goalkeeper,Left,4031553,M00271,2026-06-15,Switzerland,Group Stage,W,0,0,0,0.0,0.78,0.0,0.0

In [7]:
data.dtypes

player_id                  str
age                      int64
team                       str
position                   str
preferred_foot             str
market_value_eur         int64
match_id                   str
match_date                 str
opponent_team              str
tournament_stage           str
match_result               str
minutes_played           int64
goals                    int64
assists                  int64
expected_goals_xg      float64
pass_accuracy          float64
distance_covered_km    float64
player_rating          float64
dtype: object

## 4. Granularidad e índice

**Granularidad:** Cada fila representa la actuación individual de un jugador en un partido específico de la Copa Mundial de la FIFA 2026.

In [8]:
data.duplicated(subset=['match_id', 'player_id']).sum() # Verifica si existen registros repetidos para un mismo jugador en un mismo partido.

np.int64(0)

In [9]:
data.set_index(['match_id', 'player_id'], inplace=True) # Establece el partido y el jugador como índice compuesto.

In [10]:
data.head()

                    age   team    position preferred_foot  market_value_eur  \
match_id player_id
M00001   P00055      26  Spain  Goalkeeper           Left           4384884
         P00070      19  Spain  Midfielder          Right           4918927
         P00066      18  Spain  Midfielder           Left         125015698
         P00073      20  Spain     Forward          Right          11805512
         P00059      23  Spain    Defender           Left          13325174

                    match_date opponent_team tournament_stage match_result  \
match_id player_id
M00001   P00055     2026-07-10  South Africa      Group Stage            W
         P00070     2026-07-10  South Africa      Group Stage            W
         P00066     2026-07-10  South Africa      Group Stage            W
         P00073     2026-07-10  South Africa      Group Stage            W
         P00059     2026-07-10  South Africa      Group Stage            W

                    minutes_played  goals  assists  expected_goals_xg  \
match_id player_id
M00001   P00055                 72      0        0               0.00
         P00070                 90      0        0               0.01
         P00066                 73      1        0               0.08
         P00073                 80      1        1               0.00
         P00059                 79      0        0               0.00

                    pass_accuracy  distance_covered_km  player_rating
match_id player_id
M00001   P00055              0.59                  7.8            5.6
         P00070              0.89                 10.4            5.7
         P00066              0.85                  8.8            8.3
         P00073              0.67                  9.6            6.9
         P00059              0.76                  7.5            5.7

In [11]:
data.index.value_counts() # Muestra cuántas veces aparece cada combinación de partido y jugador.

match_id  player_id
M00001    P00053       1
          P00054       1
          P00055       1
          P00056       1
          P00057       1
                      ..
M01050    P01036       1
          P01037       1
          P01038       1
          P01039       1
          P01040       1
Name: count, Length: 54600, dtype: int64

## 5. Clasificación de las variables

In [12]:
columns_date = ['match_date']

columns_categorical = [
    'team',
    'opponent_team',
    'position',
    'preferred_foot',
    'tournament_stage',
    'match_result'
]

columns_numerical = [
    'age',
    'market_value_eur',
    'minutes_played',
    'goals',
    'assists',
    'expected_goals_xg',
    'pass_accuracy',
    'distance_covered_km',
    'player_rating'
]

In [13]:
len(columns_date) + len(columns_categorical) + len(columns_numerical) == data.shape[1] # Verifica que todas las columnas de análisis estén clasificadas.

True

## 6. Conversión de tipos de datos

In [14]:
for col_date in columns_date:
    data[col_date] = pd.to_datetime(data[col_date]) # Convierte las columnas de fecha a tipo datetime.

for col_categorical in columns_categorical:
    data[col_categorical] = data[col_categorical].astype('category') # Convierte las columnas categóricas a tipo category.

In [15]:
data.info()

<class 'pandas.DataFrame'>
MultiIndex: 54600 entries, ('M00001', 'P00055') to ('M01050', 'P00989')
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  54600 non-null  int64
 1   team                 54600 non-null  category
 2   position             54600 non-null  category
 3   preferred_foot       54600 non-null  category
 4   market_value_eur     54600 non-null  int64
 5   match_date           54600 non-null  datetime64[us]
 6   opponent_team        54600 non-null  category
 7   tournament_stage     54600 non-null  category
 8   match_result         54600 non-null  category
 9   minutes_played       54600 non-null  int64
 10  goals                54600 non-null  int64
 11  assists              54600 non-null  int64
 12  expected_goals_xg    54600 non-null  float64
 13  pass_accuracy        54600 non-null  float64
 14  distance_covered_km  54600 non-null  float64
 15  player_rating        54600 non-null  float64
dtypes: category(6), datetime64[us](1), float64(4), int64(5)
memory usage: 4.7+ MB

In [16]:
data.dtypes

age                             int64
team                         category
position                     category
preferred_foot               category
market_value_eur                int64
match_date             datetime64[us]
opponent_team                category
tournament_stage             category
match_result                 category
minutes_played                  int64
goals                           int64
assists                         int64
expected_goals_xg             float64
pass_accuracy                 float64
distance_covered_km           float64
player_rating                 float64
dtype: object

# Análisis Univariante

## 7. Análisis univariante categórico

In [ ]:
for col in columns_categorical:
    print(f"\n{'='*70}")
    print(f"ANÁLISIS DE: {col.upper()}")
    print(f"{'='*70}")

    # 1. Cantidad de categorías
    num_categories = data[col].nunique()
    print(f"\nCantidad de categorías: {num_categories}")

    # 2. Tabla de conteo y porcentajes
    value_counts = data[col].value_counts()
    percentage = (value_counts / len(data) * 100).round(2)

    table = pd.DataFrame({
        'Categoría': value_counts.index,
        'Conteo': value_counts.values,
        'Porcentaje (%)': percentage.values
    })
    table = table.reset_index(drop=True)
    print("\nTabla de conteo y porcentajes:")
    display(table)

    # 3. Gráficos para variables con menos de 10 categorías
    if num_categories < 10:
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        colors_array = plt.cm.Set2(range(num_categories))

        sns.countplot(
            data=data,
            x=col,
            ax=axes[0],
            order=value_counts.index,
            legend=False,
            width=0.75
        )

        for i, patch in enumerate(axes[0].patches):
            patch.set_facecolor(colors_array[i])

        axes[0].set_title(f'Conteo de {col}', fontsize=12, fontweight='bold')
        axes[0].set_xlabel(col, fontsize=10)
        axes[0].set_ylabel('Conteo', fontsize=10)
        axes[0].tick_params(axis='x', rotation=45)

        axes[1].pie(
            value_counts.values,
            labels=value_counts.index,
            autopct='%1.3f%%',
            startangle=180,
            colors=colors_array
        )
        axes[1].set_title(f'Distribución de {col}', fontsize=12, fontweight='bold')

        plt.tight_layout()
        plt.show()
    else:
        print(f"\nNota: {col} tiene {num_categories} categorías (≥10), no se generó gráfico.")

## 8. Análisis univariante numérico

In [ ]:
for col in columns_numerical:
    print(f"\n{'='*70}")
    print(f"ANÁLISIS DE: {col.upper()}")
    print(f"{'='*70}")

    # Tabla de estadística descriptiva
    stats = data[col].describe().to_frame().T
    print("\nEstadística descriptiva:")
    display(stats)

    # Histograma arriba y boxplot abajo
    fig, axes = plt.subplots(2, 1, figsize=(10, 8))

    sns.histplot(data=data, x=col, ax=axes[0], color='steelblue')
    axes[0].set_title(f'Histograma de {col}', fontsize=12, fontweight='bold')
    axes[0].set_xlabel(col, fontsize=10)
    axes[0].set_ylabel('Frecuencia', fontsize=10)

    sns.boxplot(data=data, x=col, ax=axes[1], color='steelblue')
    axes[1].set_title(f'Boxplot de {col}', fontsize=12, fontweight='bold')
    axes[1].set_xlabel(col, fontsize=10)

    plt.tight_layout()
    plt.show()

## 9. Análisis univariante temporal

Los conteos de esta sección representan registros jugador-partido. No representan directamente la cantidad de partidos disputados en cada fecha.

In [ ]:
for col in columns_date:
    print(f"\n{'='*70}")
    print(f"ANÁLISIS DE: {col.upper()}")
    print(f"{'='*70}")

    # Fecha mínima y máxima
    print(f"\nFecha mínima: {data[col].min()}")
    print(f"Fecha máxima: {data[col].max()}")

    # Fecha con más registros jugador-partido
    registros_por_fecha = data[col].value_counts()
    print(
        f"Fecha con más registros jugador-partido: {registros_por_fecha.index[0]} "
        f"({registros_por_fecha.iloc[0]} registros)"
    )

    fig, axes = plt.subplots(3, 1, figsize=(12, 12))

    # Distribución por año
    sns.countplot(x=data[col].dt.year, ax=axes[0], color='steelblue')
    axes[0].set_title('Distribución por año', fontsize=12, fontweight='bold')
    axes[0].set_xlabel('Año', fontsize=10)
    axes[0].set_ylabel('Cantidad de registros', fontsize=10)

    # Distribución por mes
    meses = [
        'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
    ]
    sns.countplot(x=data[col].dt.month, order=range(1, 13), ax=axes[1], color='steelblue')
    axes[1].set_title('Distribución por mes', fontsize=12, fontweight='bold')
    axes[1].set_xlabel('Mes', fontsize=10)
    axes[1].set_ylabel('Cantidad de registros', fontsize=10)
    axes[1].set_xticks(range(12))
    axes[1].set_xticklabels(meses, rotation=45)

    # Distribución por día de la semana
    dias = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
    sns.countplot(x=data[col].dt.dayofweek, order=range(7), ax=axes[2], color='steelblue')
    axes[2].set_title('Distribución por día de la semana', fontsize=12, fontweight='bold')
    axes[2].set_xlabel('Día de la semana', fontsize=10)
    axes[2].set_ylabel('Cantidad de registros', fontsize=10)
    axes[2].set_xticks(range(7))
    axes[2].set_xticklabels(dias)

    plt.tight_layout()
    plt.show()

# Análisis bivariante

## 10. Análisis bivariante numérico

In [ ]:
data[columns_numerical].corr() # Calcula la matriz de correlación entre las variables numéricas.

In [ ]:
matriz_correlaciones = data[columns_numerical].corr().round(2)

plt.figure(figsize=(10, 8))
sns.heatmap(
    matriz_correlaciones,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    vmin=-1,
    vmax=1,
    linewidths=0.5
)
plt.title('Matriz de correlaciones')
plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(10, 8))
sns.pairplot(data[columns_numerical])
plt.show()

## 11. Análisis bivariante categórico

In [ ]:
# Define aquí las dos columnas que quieres cruzar
columna_filas = 'tournament_stage'
columna_columnas = 'match_result'

# Crosstab con conteos absolutos
crosstab = pd.crosstab(
    data[columna_filas],
    data[columna_columnas]
).astype(int)

valor_min = crosstab.values.min()
valor_max = crosstab.values.max()

plt.figure(figsize=(12, 8))
sns.heatmap(
    crosstab,
    annot=True,
    fmt='d',
    cmap='RdBu_r',
    vmin=valor_min,
    vmax=valor_max,
    linewidths=2,
    linecolor='white',
    cbar_kws={'shrink': 0.85}
)
plt.title(f'Crosstab entre {columna_filas} y {columna_columnas}', fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

In [ ]:
# Define aquí las dos columnas que quieres cruzar
columna_filas = 'position'
columna_columnas = 'match_result'

plt.figure(figsize=(12, 8))
sns.countplot(
    data=data,
    x=columna_filas,
    hue=columna_columnas,
    order=data[columna_filas].value_counts().index,
    hue_order=data[columna_columnas].value_counts().index,
    palette='tab20'
)
plt.title(f'Diagrama de barras entre {columna_filas} y {columna_columnas}', fontsize=14, fontweight='bold')
plt.xlabel(columna_filas, fontsize=10)
plt.ylabel('Conteo', fontsize=10)
plt.xticks(rotation=45, ha='right')
plt.legend(title=columna_columnas, bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

## 12. Análisis categórico + numérico

In [ ]:
# Define aquí una variable categórica y una numérica
columna_categorica = 'position'
columna_numerica = 'player_rating'

print(f'Variable categórica: {columna_categorica}')
print(f'Variable numérica: {columna_numerica}')

# Boxplot comparativo por categoría
plt.figure(figsize=(12, 6))
sns.boxplot(
    data=data,
    x=columna_categorica,
    y=columna_numerica,
    color='steelblue'
)
plt.title(f'Boxplot de {columna_numerica} por {columna_categorica}', fontsize=14, fontweight='bold')
plt.xlabel(columna_categorica, fontsize=10)
plt.ylabel(columna_numerica, fontsize=10)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Histogramas en subplots separados por categoría
categorias = data[columna_categorica].dropna().unique()
num_categorias = len(categorias)
num_columnas = 2
num_filas = (num_categorias + num_columnas - 1) // num_columnas

fig, axes = plt.subplots(num_filas, num_columnas, figsize=(14, 4 * num_filas))
axes = axes.flatten() if num_categorias > 1 else [axes]

for i, categoria in enumerate(categorias):
    subset = data[data[columna_categorica] == categoria]
    sns.histplot(
        data=subset,
        x=columna_numerica,
        kde=True,
        color='steelblue',
        ax=axes[i]
    )
    axes[i].set_title(f'{columna_categorica} = {categoria}', fontsize=12, fontweight='bold')
    axes[i].set_xlabel(columna_numerica, fontsize=10)
    axes[i].set_ylabel('Frecuencia', fontsize=10)

for j in range(num_categorias, len(axes)):
    axes[j].axis('off')

fig.suptitle(f'Histogramas de {columna_numerica} por {columna_categorica}', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

## 13. Análisis temporal + categórico/numérico

In [ ]:
# Define aquí una variable numérica y una categórica para analizar su evolución temporal
columna_numerica = 'player_rating'
columna_categorica = 'match_result'
columna_tiempo = 'match_date'

print(f'Variable numérica: {columna_numerica}')
print(f'Variable categórica: {columna_categorica}')
print(f'Variable temporal: {columna_tiempo}')

# Evolución temporal de la calificación promedio por fecha
serie_numerica = data.groupby(columna_tiempo)[columna_numerica].mean().reset_index()

plt.figure(figsize=(12, 5))
sns.lineplot(
    data=serie_numerica,
    x=columna_tiempo,
    y=columna_numerica,
    color='steelblue'
)
plt.title(f'Evolución temporal del promedio de {columna_numerica}', fontsize=14, fontweight='bold')
plt.xlabel(columna_tiempo, fontsize=10)
plt.ylabel(f'Promedio de {columna_numerica}', fontsize=10)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Evolución temporal del conteo de registros por resultado
serie_categorica = (
    data.groupby([columna_tiempo, columna_categorica])
        .size()
        .reset_index(name='Conteo')
)

categorias = serie_categorica[columna_categorica].dropna().unique()
num_categorias = len(categorias)
num_columnas = 3
num_filas = (num_categorias + num_columnas - 1) // num_columnas

fig, axes = plt.subplots(
    num_filas,
    num_columnas,
    figsize=(16, 4 * num_filas),
    sharex=True,
    sharey=False
)
axes = axes.flatten() if num_categorias > 1 else [axes]

for i, categoria in enumerate(categorias):
    subset = serie_categorica[serie_categorica[columna_categorica] == categoria]
    sns.lineplot(
        data=subset,
        x=columna_tiempo,
        y='Conteo',
        ax=axes[i],
        color='steelblue'
    )
    axes[i].set_title(f'{columna_categorica} = {categoria}', fontsize=12, fontweight='bold')
    axes[i].set_xlabel(columna_tiempo, fontsize=10)
    axes[i].set_ylabel('Conteo', fontsize=10)
    axes[i].tick_params(axis='x', rotation=45)

for j in range(num_categorias, len(axes)):
    axes[j].axis('off')

fig.suptitle(f'Evolución temporal de {columna_categorica} por subgrupos', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Cinco preguntas de análisis

## Pregunta 1

**¿Los jugadores con mayor cantidad de goles esperados (`expected_goals_xg`) suelen marcar más goles?**

In [ ]:
correlacion_xg_goles = data[['expected_goals_xg', 'goals']].corr().round(3)
display(correlacion_xg_goles)

sns.pairplot(data[['expected_goals_xg', 'goals']])
plt.show()

**Conclusión:** Existe una relación positiva, pero débil, entre los goles esperados y los goles marcados. La correlación es aproximadamente **0.150**, por lo que un mayor `expected_goals_xg` se asocia con más goles, aunque por sí solo no explica gran parte de su variación.

## Pregunta 2

**¿Cómo cambia la calificación del jugador (`player_rating`) según su posición?**

In [ ]:
calificacion_por_posicion = data.groupby('position')['player_rating'].describe().round(3)
display(calificacion_por_posicion)

plt.figure(figsize=(12, 6))
sns.boxplot(
    data=data,
    x='position',
    y='player_rating',
    color='steelblue'
)
plt.title('Calificación del jugador por posición', fontsize=14, fontweight='bold')
plt.xlabel('Posición')
plt.ylabel('Calificación del jugador')
plt.tight_layout()
plt.show()

**Conclusión:** Los delanteros presentan el promedio más alto de calificación (**3.884**), seguidos de los mediocampistas (**3.861**) y defensores (**3.790**). Los porteros tienen un promedio considerablemente menor (**2.068**) y una mediana de **0**, por lo que la distribución de su calificación difiere de la de las demás posiciones.

## Pregunta 3

**¿Los jugadores de equipos ganadores obtienen mejores calificaciones que los de equipos que empatan o pierden?**

In [ ]:
calificacion_por_resultado = data.groupby('match_result')['player_rating'].describe().round(3)
display(calificacion_por_resultado)

plt.figure(figsize=(12, 6))
sns.boxplot(
    data=data,
    x='match_result',
    y='player_rating',
    color='steelblue'
)
plt.title('Calificación del jugador según el resultado', fontsize=14, fontweight='bold')
plt.xlabel('Resultado del partido')
plt.ylabel('Calificación del jugador')
plt.tight_layout()
plt.show()

**Conclusión:** Los jugadores de equipos ganadores tienen una calificación media ligeramente superior (**3.685**) a la de quienes empatan (**3.605**) o pierden (**3.606**). La diferencia es pequeña, aunque la mediana también aumenta de **5.4** a **5.6** en las victorias.

## Pregunta 4

**¿La distancia recorrida por los jugadores cambia según su posición?**

In [ ]:
distancia_por_posicion = data.groupby('position')['distance_covered_km'].describe().round(3)
display(distancia_por_posicion)

plt.figure(figsize=(12, 6))
sns.boxplot(
    data=data,
    x='position',
    y='distance_covered_km',
    color='steelblue'
)
plt.title('Distancia recorrida según la posición', fontsize=14, fontweight='bold')
plt.xlabel('Posición')
plt.ylabel('Distancia recorrida (km)')
plt.tight_layout()
plt.show()

**Conclusión:** Los mediocampistas recorren la mayor distancia promedio (**4.499 km**), seguidos de los delanteros (**4.125 km**) y defensores (**3.993 km**). Los porteros presentan la menor distancia promedio (**2.411 km**), lo cual evidencia diferencias de desplazamiento según la posición.

## Pregunta 5

**¿Cómo evoluciona la calificación promedio de los jugadores durante el torneo?**

In [ ]:
calificacion_por_fecha = (
    data.groupby('match_date')['player_rating']
        .mean()
        .reset_index()
)
display(calificacion_por_fecha)

plt.figure(figsize=(12, 5))
sns.lineplot(
    data=calificacion_por_fecha,
    x='match_date',
    y='player_rating',
    color='steelblue'
)
plt.title('Evolución de la calificación promedio durante el torneo', fontsize=14, fontweight='bold')
plt.xlabel('Fecha del partido')
plt.ylabel('Calificación promedio')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

**Conclusión:** La calificación promedio permanece relativamente estable durante el torneo, con valores diarios entre aproximadamente **3.544** y **3.701**. Aunque pasa de **3.576** en la primera fecha a **3.646** en la última, las variaciones son pequeñas y no se observa una tendencia fuerte de aumento o disminución.